import uuid
from datetime import datetime

from geoalchemy2 import Geometry
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, uuid_pk


class SatelliteObservation(Base, TimestampMixin):
    """Imagery metadata for a single satellite pass over a location (section 6).

    In this build, `is_simulated=True` observations are synthetic baseline/
    latest passes generated by MockSatelliteProvider for demo purposes -
    swapping in a real provider means this table starts getting populated by
    an actual ingestion job instead, with no change to how AIDetection or the
    risk engine consume it.
    """

    __tablename__ = "satellite_observations"

    id: Mapped[uuid.UUID] = uuid_pk()
    location: Mapped[str] = mapped_column(Geometry(geometry_type="POINT", srid=4326, spatial_index=False), nullable=False)
    provider: Mapped[str] = mapped_column(String(128), nullable=False)  # e.g. "Sentinel-2 (simulated)"
    acquisition_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolution_m: Mapped[float] = mapped_column(Float, nullable=False)
    cloud_coverage_pct: Mapped[float] = mapped_column(Float, nullable=False)
    is_simulated: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class SatelliteScan(Base, TimestampMixin):
    """Audit record of one AI change-detection scan run against an AOI -
    links the before/after observations to the AIDetection it produced."""

    __tablename__ = "satellite_scans"

    id: Mapped[uuid.UUID] = uuid_pk()
    location: Mapped[str] = mapped_column(Geometry(geometry_type="POINT", srid=4326, spatial_index=False), nullable=False)
    previous_observation_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("satellite_observations.id"), nullable=True
    )
    current_observation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("satellite_observations.id"), nullable=False
    )
    ai_detection_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("ai_detections.id"), nullable=True)
    requested_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    model_name: Mapped[str] = mapped_column(String(64), default="mock-change-detector")
    model_version: Mapped[str] = mapped_column(String(32), default="0.1.0-demo")

    previous_observation: Mapped["SatelliteObservation"] = relationship(foreign_keys=[previous_observation_id])
    current_observation: Mapped["SatelliteObservation"] = relationship(foreign_keys=[current_observation_id])
