import hashlib

from app.services.ai.llm_provider import LLMProvider

_SAMPLE_OBJECTS = [
    ("Excavator", 0.91),
    ("Exposed soil", 0.88),
    ("Vegetation clearing", 0.79),
    ("Water disturbance", 0.64),
    ("Makeshift structure", 0.55),
]

_SAMPLE_TRANSCRIPT = (
    "We arrived at the location around 10:30 in the morning and observed two "
    "excavators operating close to the river. The operators left the area "
    "when the field team arrived."
)


class MockLLMProvider(LLMProvider):
    """Deterministic demo provider. Every output is derived from its input so
    results are stable and reproducible, and always clearly DEMO-labeled by
    callers — never presented as a live model result."""

    name = "mock-llm"
    version = "0.1.0-demo"

    def generate_text(self, prompt: str, system: str | None = None) -> str:
        return (
            "[DEMO AI OUTPUT] This response was generated by the built-in demo "
            "language model (no external API key configured). Configure "
            "OPENAI_API_KEY to use a real model.\n\n"
            f"Prompt summary: {prompt.strip()[:280]}"
        )

    def transcribe_audio(self, file_path: str) -> str:
        return _SAMPLE_TRANSCRIPT

    def analyze_image(self, file_path: str) -> list[tuple[str, float]]:
        # Deterministic subset/order based on the file path hash so repeated
        # uploads of the same demo image return consistent results.
        digest = int(hashlib.sha256(file_path.encode()).hexdigest(), 16)
        count = 2 + (digest % 3)
        return _SAMPLE_OBJECTS[:count]
