import hashlib

from app.services.ai.llm_provider import ImageDetection, LLMProvider

# (label, confidence, is_countable). Countable classes get a deterministic
# quantity per file; presence-only classes never claim a count.
_SAMPLE_OBJECTS: list[tuple[str, float, bool]] = [
    ("Excavator", 0.91, True),
    ("Active mining pit", 0.86, False),
    ("Vegetation removal", 0.83, False),
    ("Exposed soil", 0.88, False),
    ("Sediment in waterway", 0.71, False),
    ("Worker", 0.68, True),
    ("Water disturbance", 0.64, False),
    ("Makeshift structure", 0.55, False),
]

_SAMPLE_TRANSCRIPT = (
    "We arrived at the location around 10:30 in the morning and observed two "
    "excavators operating close to the river. The operators left the area "
    "when the field team arrived."
)


class MockLLMProvider(LLMProvider):
    """Deterministic demo provider. Every output is derived from its input so
    results are stable and reproducible, and always clearly DEMO-labeled by
    callers - never presented as a live model result."""

    name = "mock-llm"
    version = "0.1.0-demo"

    def generate_text(self, prompt: str, system: str | None = None) -> str:
        return (
            "[DEMO AI OUTPUT] This response was generated by the built-in demo "
            "language model (no external API key configured). Configure "
            "OPENAI_API_KEY to use a real model.\n\n"
            f"Prompt summary: {prompt.strip()[:280]}"
        )

    def transcribe_audio(self, file_path: str) -> str:
        return _SAMPLE_TRANSCRIPT

    def analyze_image(self, file_path: str) -> list[ImageDetection]:
        # Deterministic subset/order/quantity based on the file path hash so
        # repeated uploads of the same demo image return consistent results.
        digest = int(hashlib.sha256(file_path.encode()).hexdigest(), 16)
        n = 2 + (digest % 3)
        results = []
        for i, (label, confidence, countable) in enumerate(_SAMPLE_OBJECTS[:n]):
            count = None
            if countable:
                # A different slice of the hash per label so quantities vary independently.
                count = 1 + ((digest >> (i * 4)) % 3)
            results.append(ImageDetection(label=label, confidence=confidence, count=count))
        return results
