"""initial schema

Revision ID: 0ecb014a06c8
Revises: 
Create Date: 2026-09-14 16:00:10.363783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ecb014a06c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forest_reserves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('protected_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area_type', sa.String(length=32), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capital', sa.String(length=128), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('water_bodies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('water_type', sa.String(length=32), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capital', sa.String(length=128), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=128), nullable=True),
    sa.Column('generated_query', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', 'PUSH', name='notification_channel'), nullable=False),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('community_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.Enum('SUSPECTED_ILLEGAL_MINING', 'LAND_DISTURBANCE', 'WATER_POLLUTION', 'VEGETATION_LOSS', 'UNAUTHORIZED_EQUIPMENT', 'OTHER', name='incident_type'), nullable=False),
    sa.Column('source_type', sa.Enum('FIELD_REPORT', 'PUBLIC_REPORT', 'AI_DETECTION', 'ANALYST_ENTRY', name='source_type'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUIRED', 'VERIFIED', 'UNVERIFIED', 'CLOSED', 'ARCHIVED', name='incident_status'), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'SENSITIVE', 'RESTRICTED', name='data_classification'), nullable=False),
    sa.Column('environmental_impact', sa.Text(), nullable=True),
    sa.Column('water_body_affected', sa.Boolean(), nullable=False),
    sa.Column('protected_area_affected', sa.Boolean(), nullable=False),
    sa.Column('equipment_observed', sa.String(length=255), nullable=True),
    sa.Column('estimated_people_present', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_reference_number'), 'incidents', ['reference_number'], unique=True)
    op.create_table('ai_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('detection_type', sa.Enum('VEGETATION_LOSS', 'EXPOSED_SOIL', 'EXCAVATION', 'NEW_ROAD', 'PIT_EXPANSION', 'WATER_SEDIMENTATION', name='detection_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('estimated_area_hectares', sa.Float(), nullable=True),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_observation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'USEFUL', 'NOT_USEFUL', 'CONFIRMED', 'REJECTED', 'NEEDS_REVIEW', name='ai_review_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='evidence_file_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('original_audio_path', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('officer_approved', sa.Boolean(), nullable=False),
    sa.Column('officer_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('NEW', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUIRED', 'VERIFIED', 'UNVERIFIED', 'CLOSED', 'ARCHIVED', name='incident_status'), nullable=True),
    sa.Column('new_status', sa.Enum('NEW', 'UNDER_REVIEW', 'FIELD_VERIFICATION_REQUIRED', 'VERIFIED', 'UNVERIFIED', 'CLOSED', 'ARCHIVED', name='incident_status'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_status_history_incident_id'), 'incident_status_history', ['incident_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('REPORT', 'AI_TRIAGE', 'HUMAN_REVIEW', 'FIELD_VERIFICATION', 'EVIDENCE_COLLECTION', 'INVESTIGATION', 'RESOLUTION', 'CLOSED', name='investigation_stage'), nullable=False),
    sa.Column('lead_officer_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('LOW', 'MODERATE', 'ELEVATED', 'HIGH', 'CRITICAL', name='risk_category'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_incident_id'), 'risk_scores', ['incident_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('assigned_team_id', sa.UUID(), nullable=True),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_versions_evidence_id'), 'evidence_versions', ['evidence_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_risk_score_id'), 'risk_factors', ['risk_score_id'], unique=False)

    # --- Manual GIST spatial indexes (geoalchemy2 columns use spatial_index=False
    # to avoid a double-CREATE-INDEX conflict with autogenerate; indexes are
    # created explicitly here instead — section 54). ---
    op.create_index('idx_regions_centroid', 'regions', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_districts_centroid', 'districts', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_communities_location', 'communities', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_water_bodies_geom', 'water_bodies', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_protected_areas_geom', 'protected_areas', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_forest_reserves_geom', 'forest_reserves', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_ai_detections_location', 'ai_detections', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_risk_scores_location', 'risk_scores', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_evidence_location', 'evidence', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_field_reports_location', 'field_reports', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_field_reports_location', table_name='field_reports', postgresql_using='gist')
    op.drop_index('idx_evidence_location', table_name='evidence', postgresql_using='gist')
    op.drop_index('idx_risk_scores_location', table_name='risk_scores', postgresql_using='gist')
    op.drop_index('idx_ai_detections_location', table_name='ai_detections', postgresql_using='gist')
    op.drop_index('idx_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_index('idx_forest_reserves_geom', table_name='forest_reserves', postgresql_using='gist')
    op.drop_index('idx_protected_areas_geom', table_name='protected_areas', postgresql_using='gist')
    op.drop_index('idx_water_bodies_geom', table_name='water_bodies', postgresql_using='gist')
    op.drop_index('idx_communities_location', table_name='communities', postgresql_using='gist')
    op.drop_index('idx_districts_centroid', table_name='districts', postgresql_using='gist')
    op.drop_index('idx_regions_centroid', table_name='regions', postgresql_using='gist')

    op.drop_index(op.f('ix_risk_factors_risk_score_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_evidence_versions_evidence_id'), table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_risk_scores_incident_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('report_sources')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_incident_status_history_incident_id'), table_name='incident_status_history')
    op.drop_table('incident_status_history')
    op.drop_table('field_reports')
    op.drop_table('evidence')
    op.drop_table('ai_detections')
    op.drop_index(op.f('ix_incidents_reference_number'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('reports')
    op.drop_table('operations')
    op.drop_table('officers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('communities')
    op.drop_table('audit_logs')
    op.drop_table('ai_queries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('role_permissions')
    op.drop_table('districts')
    op.drop_table('water_bodies')
    op.drop_table('system_settings')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('protected_areas')
    op.drop_table('permissions')
    op.drop_table('forest_reserves')
    # ### end Alembic commands ###
