"""satellite observations and scans

Revision ID: 3281c9e5f0a9
Revises: ac2894f041fe
Create Date: 2026-09-14 19:16:18.525654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3281c9e5f0a9'
down_revision: Union[str, None] = 'ac2894f041fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_m', sa.Float(), nullable=False),
    sa.Column('cloud_coverage_pct', sa.Float(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('previous_observation_id', sa.UUID(), nullable=True),
    sa.Column('current_observation_id', sa.UUID(), nullable=False),
    sa.Column('ai_detection_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_detection_id'], ['ai_detections.id'], ),
    sa.ForeignKeyConstraint(['current_observation_id'], ['satellite_observations.id'], ),
    sa.ForeignKeyConstraint(['previous_observation_id'], ['satellite_observations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.create_index('idx_satellite_observations_location', 'satellite_observations', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_satellite_scans_location', 'satellite_scans', ['location'], unique=False, postgresql_using='gist')


def downgrade() -> None:
    op.drop_index('idx_satellite_scans_location', table_name='satellite_scans', postgresql_using='gist')
    op.drop_index('idx_satellite_observations_location', table_name='satellite_observations', postgresql_using='gist')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satellite_scans')
    op.drop_table('satellite_observations')
    # ### end Alembic commands ###
