"use client";

import { useState } from "react";
import { Topbar } from "@/components/Topbar";
import { MarkdownLite } from "@/components/MarkdownLite";
import { api, ApiError } from "@/lib/api";
import type { ReportOut } from "@/lib/types";

const REPORT_TYPES: { value: string; label: string }[] = [
  { value: "press_briefing", label: "Press Briefing" },
  { value: "social_media_briefing", label: "Social Media Briefing" },
  { value: "weekly_situation", label: "Situation Report" },
  { value: "parliamentary_briefing", label: "Parliamentary Briefing" },
  { value: "media_qa", label: "Media Q&A" },
  { value: "executive_brief", label: "Executive Brief" },
  { value: "talking_points", label: "Talking Points" },
];

export default function CommunicationsPage() {
  const [reportType, setReportType] = useState("executive_brief");
  const [report, setReport] = useState<ReportOut | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setReport(null);
    try {
      const r = await api.post<ReportOut>("/api/reports/generate", { report_type: reportType });
      setReport(r);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to generate report");
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <Topbar title="Communications Centre" />
      <div className="p-6 max-w-3xl mx-auto w-full space-y-5">
        <div className="bg-surface border border-border rounded-lg p-5">
          <h2 className="text-sm font-semibold text-navy-900 mb-3">Generate Communication</h2>
          <div className="flex flex-wrap gap-3">
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="rounded-md border border-border px-3 py-2 text-sm"
            >
              {REPORT_TYPES.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
            <button
              onClick={generate}
              disabled={loading}
              className="rounded-md bg-navy-800 text-white text-sm font-medium px-4 py-2 hover:bg-navy-700 disabled:opacity-50"
            >
              {loading ? "Generating…" : "Generate"}
            </button>
          </div>
          <p className="text-xs text-slate-400 mt-3">
            Every figure below is pulled directly from verified database records. Sections labeled
            AI-GENERATED INTERPRETATION reflect risk analysis, not confirmed fact - see the underlying incident IDs
            for traceability.
          </p>
        </div>

        {error && <p className="text-sm text-red-600">{error}</p>}

        {report && (
          <div className="bg-surface border border-border rounded-lg p-6">
            <MarkdownLite content={report.content_markdown} />
            <div className="mt-6 pt-4 border-t border-border text-[11px] text-slate-400">
              Generated by {report.model_name} {report.model_version} · {report.source_incident_ids.length} source
              record(s) · {report.created_at.slice(0, 16).replace("T", " ")}
            </div>
          </div>
        )}
      </div>
    </>
  );
}

