"use client";

import { useState } from "react";
import { Topbar } from "@/components/Topbar";
import { api, ApiError } from "@/lib/api";
import type { ReportOut } from "@/lib/types";

const REPORT_TYPES: { value: string; label: string }[] = [
  { value: "executive_brief", label: "Executive Brief" },
  { value: "press_briefing", label: "Press Briefing" },
  { value: "weekly_situation", label: "Weekly Situation Summary" },
  { value: "talking_points", label: "Talking Points" },
  { value: "media_qa", label: "Media Q&A Preparation" },
];

export default function CommunicationsPage() {
  const [reportType, setReportType] = useState("executive_brief");
  const [report, setReport] = useState<ReportOut | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setReport(null);
    try {
      const r = await api.post<ReportOut>("/api/reports/generate", { report_type: reportType });
      setReport(r);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to generate report");
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <Topbar title="Communications Centre" />
      <div className="p-6 max-w-3xl mx-auto w-full space-y-5">
        <div className="bg-surface border border-border rounded-lg p-5">
          <h2 className="text-sm font-semibold text-navy-900 mb-3">Generate Communication</h2>
          <div className="flex flex-wrap gap-3">
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="rounded-md border border-border px-3 py-2 text-sm"
            >
              {REPORT_TYPES.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
            <button
              onClick={generate}
              disabled={loading}
              className="rounded-md bg-navy-800 text-white text-sm font-medium px-4 py-2 hover:bg-navy-700 disabled:opacity-50"
            >
              {loading ? "Generating…" : "Generate"}
            </button>
          </div>
          <p className="text-xs text-slate-400 mt-3">
            Every figure below is pulled directly from verified database records. Sections labeled
            AI-GENERATED INTERPRETATION reflect risk analysis, not confirmed fact — see the underlying incident IDs
            for traceability.
          </p>
        </div>

        {error && <p className="text-sm text-red-600">{error}</p>}

        {report && (
          <div className="bg-surface border border-border rounded-lg p-6">
            <MarkdownLite content={report.content_markdown} />
            <div className="mt-6 pt-4 border-t border-border text-[11px] text-slate-400">
              Generated by {report.model_name} {report.model_version} · {report.source_incident_ids.length} source
              record(s) · {report.created_at.slice(0, 16).replace("T", " ")}
            </div>
          </div>
        )}
      </div>
    </>
  );
}

/** Minimal markdown renderer (headings, bullet lists, bold) — avoids pulling
 * in a full markdown dependency for this demo report viewer. */
function MarkdownLite({ content }: { content: string }) {
  const lines = content.split("\n");
  return (
    <div className="space-y-1.5 text-sm text-navy-900">
      {lines.map((line, i) => {
        if (line.startsWith("# ")) return <h1 key={i} className="text-lg font-semibold mt-2">{line.slice(2)}</h1>;
        if (line.startsWith("## ")) return <h2 key={i} className="text-sm font-semibold text-navy-900 mt-4">{line.slice(3)}</h2>;
        if (line.startsWith("- ")) return <p key={i} className="pl-4 text-sm">• {line.slice(2)}</p>;
        if (line.startsWith("  - ")) return <p key={i} className="pl-8 text-xs text-slate-600">◦ {line.slice(4)}</p>;
        if (line.trim() === "") return <div key={i} className="h-1" />;
        if (line.includes("DEMO ENVIRONMENT"))
          return (
            <p key={i} className="inline-block text-xs font-semibold text-amber-800 bg-amber-50 border border-amber-200 rounded px-2 py-1">
              {line}
            </p>
          );
        return <p key={i} className="text-sm">{line}</p>;
      })}
    </div>
  );
}
